apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appapinode-pv-claim
  labels:
    app: appapinode
spec:
  storageClassName: azuredisk-premium-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: default
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        imagePullPolicy: Always
        image: appapinode.azurecr.io/appapinode:latest
        volumeMounts:
        - name: appapinode-persistent-storage
          mountPath: /app
        ports:
        - containerPort: 3000
      volumes:
      - name: appapinode-persistent-storage
        persistentVolumeClaim:
          claimName: appapinode-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
