kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata: 
  name: azuredisk-preminum-retain 
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true 
parameters:
  stroageaccounttype: Premium_LRS
  kind: Managed
