apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "global.labels" . | nindent 4 | trim }}
  name: {{ .Values.global.stack }}-clevertap-api-secrets
type: Opaque
data:
  {{- range $k, $v := .Values.services.clevertap_api.secret }}
  {{ $k }}: {{ $v | b64enc}}
  {{- end -}}
  {{- range $k, $v := .Values.services.clevertap_api.secret_b64 }}
  {{ $k }}: {{ $v }}
  {{- end -}}
